massive_homework/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="index.html")),
    path("showcase/", include("showcase_app.urls")),
    path(
        "user/",
        include("user_app.urls"),
    ),
    path(
        "user/",
        include("django.contrib.auth.urls"),
    ),
]


if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_app/urls.py
from django.urls import path, include
from .views import (
    register,
    user_login,
    edit,
    edit_user,
    dashboard,
    UserDetailView,
)

app_name = "user_app"


urlpatterns = [
    # post views
    path("dashboard/", dashboard, name="dashboard"),
    path(
        "<int:pk>/",
        UserDetailView.as_view(template_name="user_app/user_detail.html"),
        name="userprofile",
    ),
    path("login/", user_login, name="login"),
    path("register/", register, name="register"),
    path("edit/", edit, name="edit"),
    path("edit/<int:pk>/", edit_user, name="edit-user"),
]

user_app/models.py
from django.db import models
from django.conf import settings

# Create your models here.


class BaseUser(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    bio = models.TextField(blank=True, null=True)
    prof_pic = models.ImageField(upload_to="images/%Y/%m/%d", blank=True, null=True)
    moder = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    archived = models.BooleanField(default=False)

    def __str__(self):
        return "Profile for user {}".format(self.user.username)

user_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import BaseUser


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repeat password", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("username", "first_name", "email")

    def clean_password2(self):
        cd = self.cleaned_data
        if cd["password"] != cd["password2"]:
            raise forms.ValidationError("Passwords don't match.")
        return cd["password2"]


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email")


class BaseUserEditForm(forms.ModelForm):
    class Meta:
        model = BaseUser
        fields = ("bio", "prof_pic")

user_app/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.views.generic import DetailView

from .forms import UserRegistrationForm, LoginForm, UserEditForm, BaseUserEditForm
from .models import BaseUser


@login_required
def dashboard(request):
    return render(request, "user_app/dashboard.html", {"section": "dashboard"})


# @login_required
class UserDetailView(DetailView):
    model = User


def user_login(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd["username"], password=cd["password"])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(reverse("user_app:dashboard"))
                else:
                    return HttpResponse("Disabled account")
            else:
                return HttpResponse("Invalid login")
    else:
        form = LoginForm()
    return render(request, "user_app/login.html", {"form": form})


def register(request):
    if request.method == "POST":
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data["password"])
            new_user.save()
            base_user = BaseUser.objects.create(user=new_user)
            return render(
                request, "user_app/register_done.html", {"new_user": new_user}
            )
    else:
        user_form = UserRegistrationForm()
    return render(request, "user_app/register.html", {"user_form": user_form})


@login_required
def edit(request):
    if request.method == "POST":
        user_form = UserEditForm(instance=request.user, data=request.POST)
        base_edit_form = BaseUserEditForm(
            instance=request.user.baseuser, data=request.POST, files=request.FILES
        )
        if user_form.is_valid() and base_edit_form.is_valid():
            user_form.save()
            base_edit_form.save()
            return render(
                request,
                "user_app/dashboard.html",
            )
    else:
        user_form = UserEditForm(instance=request.user)
        base_edit_form = BaseUserEditForm(instance=request.user.baseuser)
        return render(
            request,
            "user_app/edit.html",
            {"user_form": user_form, "base_user_form": base_edit_form},
        )


def edit_user(request, pk, **kwargs):
    if request.method == "POST":
        user_data = User.objects.get(pk=pk)
        user_form = UserEditForm(instance=user_data, data=request.POST)
        base_edit_form = BaseUserEditForm(
            instance=BaseUser.objects.get(user_id=user_data.pk),
            data=request.POST,
            files=request.FILES,
        )
        if user_form.is_valid() and base_edit_form.is_valid():
            user_form.save()
            base_edit_form.save()
            return HttpResponseRedirect(
                reverse(
                    "user_app:userprofile",
                    kwargs={"pk": user_data.pk},
                )  # pk=user_data.pk)
            )
    else:
        user_data = User.objects.get(pk=pk)
        user_form = UserEditForm(instance=user_data)
        base_edit_form = BaseUserEditForm(instance=user_data.baseuser)
        return render(
            request,
            "user_app/edit_user.html",
            {
                "user_form": user_form,
                "base_user_form": base_edit_form,
                "user": user_data,
            },
        )

user_app/templates/user_app/dashboard.html
{% extends "base.html" %}

{% block title %}Личный кабинет{% endblock %}

{% block body %}
    <h1>Личный кабинет</h1>
    <p>Это ваш личный кабинет. Вы можете <a href="{% url "user_app:edit" %}">отредактировать профиль</a> или <a href="{% url "password_change" %}">поменять пароль</a>.</p></p>
   <h2>Юзернейм: {{ user }}</h2>
    <h2>О себе:</h2>
    {% if user.baseuser.bio %}
    {{ user.baseuser.bio }}
    {% else %}
        Пользователь пока ничего не написал
    {% endif %}
    <h2>Имя: {{ user.first_name }}</h2>
    <h2>Фото:</h2>
    {% if user.baseuser.prof_pic %}
    <div class="my-3 d-flex justify-content-left">
      <img src="{{ user.baseuser.prof_pic.url }}" alt="connect"  style="max-height:300px;">
{#        #"width: 100%; float: left; margin-right: 10px;">#}
    </div>
    {% else %}
        Нет фото :с
    {% endif %}
    <h1>Выход</h1>
    <p>Для того чтобы выйти, нажми <a href="{% url "logout" %}">выйти</a>.</p>
{% endblock %}

user_app/templates/user_app/edit.html
{% extends "base.html" %}

{% block title %}Редактор профиля{% endblock %}

{% block body %}
    {% if user.is_authenticated %}
    <h1>Редактирование информации о себе</h1>
    <p>Используя форму ниже, вы можете изменить информацию о себе:</p>
    <form action="." method="post" enctype="multipart/form-data">
        {{ user_form.as_p }}
        {{ base_user_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Save changes"></p>
    </form>
    {% else %}

    {% endif %}
{% endblock %}

user_app/templates/user_app/edit_user.html
{% extends "base.html" %}

{% block title %}Редактор профиля{% endblock %}

{% block body %}
     {% if request.user.baseuser.moder or request.user.is_staff %}
    <h1>Редактирование информации пользователя {{ user.username }}</h1>
    <p>Используя форму ниже, вы можете изменить информацию пользователя:</p>

    <form action="." method="post" enctype="multipart/form-data">
        {{ user_form.as_p }}
        {{ base_user_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Save changes"></p>
    </form>
    {% else %}
    <h1>Вам сюда нельзя</h1>
    {% endif %}
{% endblock %}

user_app/templates/user_app/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}

{% block body %}

  {% if form.errors %}
    <p>Пара Юзернейм-Пароль не совпадают, пожалуйста, повторите.</p>
  {% endif %}

  {% if next %}
    {% if user.is_authenticated %}
      <p>У вас нет доступа к этой странице. Чтобы продолжить, войдите в соответствующий профиль.</p>
    {% else %}
      <p>Пожалуйста, войдите, чтобы продолжить.</p>
    {% endif %}
  {% endif %}

  <form method="post" action="{% url 'login' %}">
    {% csrf_token %}
    <table>
      <tr>
        <td>{{ form.username.label_tag }}</td>
        <td>{{ form.username }}</td>
      </tr>
      <tr>
        <td>{{ form.password.label_tag }}</td>
        <td>{{ form.password }}</td>
      </tr>
    </table>
    <input type="submit" value="login">
    <input type="hidden" name="next" value="{{ next }}">
  </form>

  {# Assumes you setup the password_reset view in your URLconf #}
  <p><a href="{% url 'password_reset' %}">Забыли пароль?</a></p>
  <p><a href="{% url 'user_app:register' %}">Регистрация</a></p>

{% endblock %}

user_app/templates/user_app/register.html
{% extends "base.html" %}

{% block title %}Создание пользователя{% endblock %}

{% block body %}
    <h1>Создание пользователя</h1>
    <p>Чтобы зарегистрироваться, используйте форму::</p>
    <form action="." method="post">
        {{ user_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Create my account"></p>
    </form>
{% endblock %}

user_app/templates/user_app/register_done.html
{% extends "base.html" %}

{% block title %}Привет!{% endblock %}

{% block body %}
    <h1>Привет, {{ new_user.first_name }}!</h1>
    <p>Ваш профиль был создан. Теперь вы можете <a href="{% url "user_app:login" %}">войти</a>.</p>
{% endblock %}

user_app/templates/user_app/user_detail.html
{% extends "base.html" %}

{% block title %}User{% endblock %}

{% block body %}
    <h1>Личный кабинет пользователя {{ user.username }}</h1>
      {% if request.user.baseuser.moder or request.user.is_staff %}
    <p>Это личный кабинет пользователя {{ user.username }}. Вы можете <a href="{% url "user_app:edit-user" pk=user.pk %}">отредактировать его профиль</a>.</p>
    {% endif %}
    <h2>Юзернейм: {{ user }}</h2>
    <h2>О себе:</h2>
    {% if user.baseuser.bio %}
    {{ user.baseuser.bio }}
    {% else %}
        Пользователь пока ничего не написал
    {% endif %}
    <h2>Имя: {{ user.first_name }}</h2>
    <h2>Фото:</h2>
    {% if user.baseuser.prof_pic %}
    <div class="my-3 d-flex justify-content-left">
      <img src="{{ user.baseuser.prof_pic.url }}" alt="connect"  style="max-height:300px;">
    </div>
    {% else %}
        Нет фото :с
    {% endif %}
{% endblock %}