massive_homework/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="index.html")),
    path("showcase/", include("showcase_app.urls")),
    path(
        "user/",
        include("user_app.urls"),
    ),
    path(
        "user/",
        include("django.contrib.auth.urls"),
    ),
]


if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

showcase_app/urls.py
from django.urls import path

from .views import (
    ProductListView,
    ProductCreateView,
    ProductDetailView,
    ProductUpdateView,
    ProductDeleteView,
    QuestionDetailView,
    QuestionDeleteView,
    QuestionListView,
    AnswerDeleteView,
)


app_name = "showcase_app"

urlpatterns = [
    path("products/", ProductListView.as_view(), name="index"),
    path("product/<int:pk>/", ProductDetailView.as_view(), name="product"),
    path("product/create/", ProductCreateView.as_view(), name="create-product"),
    path(
        "product/<int:pk>/update/", ProductUpdateView.as_view(), name="update-product"
    ),
    path(
        "product/<int:pk>/delete/", ProductDeleteView.as_view(), name="delete-product"
    ),
    path("question/<int:pk>/", QuestionDetailView.as_view(), name="question"),
    path(
        "question/<int:pk>/delete/",
        QuestionDeleteView.as_view(),
        name="delete-question",
    ),
    path(
        "answer/<int:pk>/delete/",
        AnswerDeleteView.as_view(),
        name="delete-answer",
    ),
    path(
        "product/<int:pk>/questions/", QuestionListView.as_view(), name="question-list"
    ),
]

user_app/urls.py
from django.urls import path, include
from .views import (
    register,
    user_login,
    edit,
    edit_user,
    dashboard,
    UserDetailView,
)

app_name = "user_app"


urlpatterns = [
    # post views
    path("dashboard/", dashboard, name="dashboard"),
    path(
        "<int:pk>/",
        UserDetailView.as_view(template_name="user_app/user_detail.html"),
        name="userprofile",
    ),
    path("login/", user_login, name="login"),
    path("register/", register, name="register"),
    path("edit/", edit, name="edit"),
    path("edit/<int:pk>/", edit_user, name="edit-user"),
]

showcase_app/models.py
from django.db import models
from user_app.models import BaseUser
from django.conf import settings

# Create your models here.


class Product(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    name = models.CharField(max_length=100)
    description = models.TextField()
    images = models.ImageField(upload_to="images/%Y/%m/%d", blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    archived = models.BooleanField(default=False)

    def __str__(self):
        return f"Вещь <{self.pk}, {self.name!r} >"

    def __int__(self):
        return self.pk


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    body = models.TextField()
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    archived = models.BooleanField(default=False)


class Question(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    header = models.CharField(max_length=100)
    body = models.TextField()
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    archived = models.BooleanField(default=False)


class Answer(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    body = models.TextField()
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    archived = models.BooleanField(default=False)

showcase_app/forms.py
from django import forms
from django.http import request

from .models import Product, Comment, Question, Answer


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "name", "description", "images"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for name, field in self.fields.items():
            print(name, field)
            field: forms.Field
            widget: forms.Widget = field.widget
            widget.attrs["class"] = "form-control"
            if isinstance(field, forms.CharField):
                print(field.label, type(field.label))


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("body",)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for name, field in self.fields.items():
            print(name, field)
            field: forms.Field
            widget: forms.Widget = field.widget
            widget.attrs["class"] = "form-control"
            if isinstance(field, forms.CharField):
                print(field.label, type(field.label))


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = "header", "body"
        widgets = {"product": forms.HiddenInput()}


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ("body",)
        widgets = {"question": forms.HiddenInput()}

showcase_app/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.urls import reverse, reverse_lazy
from django.db.models import Q, Count
from django.views.generic import (
    ListView,
    CreateView,
    DetailView,
    UpdateView,
    DeleteView,
)
from pathlib import Path
import os

from django.views.generic.edit import FormMixin

from .models import Product, Question, Answer
from .forms import ProductForm, QuestionForm, AnswerForm
from massive_homework.settings import BASE_DIR

# Create your views here.

### PRODUCTS VIEWS ###


class ProductListView(ListView):
    queryset = Product.objects.all()


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    exclude = ["user"]

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    success_url = reverse_lazy("showcase_app:index")


class ProductDetailView(FormMixin, DetailView):
    model = Product
    path_input_image = Product.images
    path_input_image_abs = f"{BASE_DIR}/{path_input_image}"
    form_class = QuestionForm

    def get_context_data(self, **kwargs):
        question = (
            Question.objects.annotate(number_of_answers=Count("answer"))
            .filter(~Q(archived=True), product_id=self.get_object())
            .order_by("created_at")
        )
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context["form"] = QuestionForm(
            initial={"user_id": self.request.user.pk, "product": self.object}
        )
        context["question"] = question
        return context

    def post(self, request, *args, **kwargs):
        new_question = Question(
            user=request.user,
            header=request.POST.get("header"),
            body=request.POST.get("body"),
            product_id=self.get_object(),
        )
        new_question.save()
        return self.get(self, request, *args, **kwargs)


class ProductUpdateView(UpdateView):
    template_name_suffix = "_update_form"
    model = Product
    form_class = ProductForm

    def get_success_url(self):
        return reverse("showcase_app:product", kwargs={"pk": self.object.pk})


class ProductDeleteView(DeleteView):
    success_url = reverse_lazy("showcase_app:index")
    queryset = Product.objects.filter(~Q(archived=True)).all()


### QUESTION VIEWS ###


class QuestionDetailView(FormMixin, DetailView):
    model = Question
    form_class = AnswerForm

    def get_context_data(self, **kwargs):
        answer = Answer.objects.filter(question_id=self.get_object()).order_by("id")
        context = super(QuestionDetailView, self).get_context_data(**kwargs)
        context["form"] = AnswerForm(
            initial={"user_id": self.request.user.pk, "question": self.object}
        )
        context["answer"] = answer
        return context

    # @login_required
    def post(self, request, *args, **kwargs):
        new_answer = Answer(
            user=request.user,
            body=request.POST.get("body"),
            question_id=self.get_object().id,
        )
        new_answer.save()
        return self.get(self, request, *args, **kwargs)


class QuestionDeleteView(DeleteView):
    queryset = Question.objects.filter(~Q(archived=True)).all()

    def get_success_url(self):
        return reverse("showcase_app:product", kwargs={"pk": self.object.product.pk})


class QuestionListView(ListView):
    model = Question

    def get_queryset(self, **kwargs):
        qs = super().get_queryset(**kwargs)
        return qs.filter(product_id=self.kwargs["pk"])


class AnswerDeleteView(DeleteView):
    queryset = Answer.objects.filter(~Q(archived=True)).all()

    def get_success_url(self):
        return reverse("showcase_app:question", kwargs={"pk": self.object.question.pk})

showcase_app/templates/showcase_app/answer_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
  Архивировать ответ #{{ answer.pk }}
{% endblock %}

{% block body %}
     {% if request.user.pk in answer.user.pk or request.user.baseuser.moder or request.user.is_staff %}

  <h1>Архивировать ответ?</h1>


  <form method="post">
    {% csrf_token %}
    <input class="btn btn-warning" type="submit" value="Archive">
  </form>

    {% else %}
    <h1>Вам сюда нельзя</h1>
    {% endif %}

  <div>
    <a class="btn btn-sm btn-info" href="{% url 'showcase_app:question' pk=answer.question_id %}">Назад к вопросу</a>
  </div>
{% endblock %}

showcase_app/templates/showcase_app/product_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
  Архивировать товар #{{ product.pk }}
{% endblock %}

{% block body %}
     {% if request.user.pk in product.user.pk or request.user.baseuser.moder or request.user.is_staff %}
      <h1>Архивировать <code>{{ product.name }}</code></h1>
  <div class="alert alert-danger">
    Вы уверены, что хотите архивировать товар #{{ product.pk }}
    с именем <code>{{ product.name }}</code>?
  </div>

  <form method="post">
    {% csrf_token %}
    <input class="btn btn-warning" type="submit" value="Archive">
  </form>
    {% else %}
    <h1>Вам сюда нельзя</h1>
    {% endif %}


  <div>
    <a class="btn btn-sm btn-info" href="{% url 'showcase_app:product' pk=product.pk %}">Назад к подробностям</a>
  </div>
{% endblock %}

showcase_app/templates/showcase_app/product_detail.html
{% extends 'base.html' %}

{% block title %}
  Товар #{{ product.pk }}
{% endblock %}

{% block body %}
    <h1>О товаре №{{ product.pk }}, создан пользователем  <a href="{% url "user_app:userprofile" pk=product.user.pk %}">{{ product.user.username }}</a> </h1>
  <h2><code>{{ product.name }}</code></h2>
  <h3>Описание:</h3>
  <p>{{ product.description }}</p>
  <h3>Создан:</h3>
  <p>{{ product.created_at }}</p>

    {% if product.images %}
        <h3>Фото:</h3>
    <div class="my-3 d-flex justify-content-left">
      <img src="{{ product.images.url }}" alt="connect"  style="max-height:300px;">
    </div>
    {% endif %}

    <h3>Обновлен:</h3>
  <p>{{ product.updated_at }}</p>

    <h3>Вопросы о товаре:</h3>
    <a class="text-decoration-none"
               href="{% url 'showcase_app:question-list' pk=product.pk %}"
        ><p>Все вопросы к товару</p></a>
    <h3>________</h3>
        {% for obj in question %}

            <a class="text-decoration-none"
               href="{% url 'showcase_app:question' pk=obj.pk %}"
        ><h4>{{ obj.header }}</h4></a>
            <h5>{{ obj.body }}</h5>
            Автор: <a href="{% url "user_app:userprofile" pk=obj.user.pk %}">{{ obj.user.username }}</a>,
            <p>Ответов: {{ obj.number_of_answers }},</p>
            Задан: {{ obj.created_at }}
          <h3>________</h3>
        {% endfor %}
      <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            {{ form }}
            <button class="btn btn-info" type="submit">Отправить! </button>
        </div>
      </form>




  <p>{{ form.question }}</p>

  <div>
       {% if request.user.pk in product.user.pk or request.user.baseuser.moder or request.user.is_staff %}
    <a class="btn btn-success" href="{% url 'showcase_app:update-product' pk=product.pk %}">Редактировать</a>
    <a class="btn btn-warning" href="{% url 'showcase_app:delete-product' pk=product.pk %}">Архивировать</a>
      {% endif %}
    <ul>
      <li>
        <a href="{% url 'showcase_app:index' %}">Назад к витрине</a>
      </li>
    </ul>
  </div>

{% endblock %}

showcase_app/templates/showcase_app/product_form.html
{% extends 'base.html' %}

{% block title %}
  Создать товар
{% endblock %}

{% block body %}

  <h2>Создать товар</h2>
    {% if user.is_authenticated %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <input class="btn btn-primary" type="submit" value="Создать">
  </form>
    {% else %}
    <h3>Вы не можете создать товар, пока не вошли в свой аккаунт</h3>
    <a
        class="btn btn-outline-primary"
        href="{% url 'login' %}">
        Login
      </a>
    {% endif %}
{% endblock %}

showcase_app/templates/showcase_app/product_list.html
{% extends 'base.html' %}

{% block title %}
  Витрина
{% endblock %}

{% block body %}
  <h1>Витрина:</h1>
    <h3>Товар: Описание</h3>
  <div>
    <ul>
      {% for product in product_list %}
        <li><a class="text-decoration-none"
               href="{% url 'showcase_app:product' pk=product.pk %}"
        >{{ product.name }}</a>: {{ product.description }}, автор: {{ product.user.username }}
        </li>
          {% empty %}
          <h3>Пока пусто!</h3>
      {% endfor %}
    </ul>
  </div>
    {% if user.is_authenticated %}
  <div>
     <a href="{% url 'showcase_app:create-product' %}">Создать товар</a>
  </div>
    {% else %}
      <a
        class="btn btn-outline-primary"
        href="{% url 'login' %}">
        Login
      </a>
    {% endif %}
{% endblock %}

showcase_app/templates/showcase_app/product_update_form.html
{% extends 'base.html' %}

{% block title %}
  Изменить товар #{{ category.pk }}
{% endblock %}

{% block body %}
     {% if request.user.pk in product.user.pk or request.user.baseuser.moder or request.user.is_staff %}
  <h2>Изменить товар #{{ product.pk }} с именем <code>{{ product.name }}</code></h2>
  <form class="my-3" method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <input class="btn btn-primary" type="submit" value="Изменить">
  </form>
    {% else %}
    <h1>Вам сюда нельзя</h1>
    {% endif %}
  <div>
    <a class="btn btn-sm btn-info" href="{% url 'showcase_app:product' pk=product.pk %}">Назад к товару</a>
  </div>
{% endblock %}

showcase_app/templates/showcase_app/question_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
  Архивировать вопрос #{{ question.pk }}
{% endblock %}

{% block body %}
     {% if request.user.pk in product.user.pk or request.user.baseuser.moder or request.user.is_staff %}
  <h1>Архивировать вопрос?</h1>


  <form method="post">
    {% csrf_token %}
    <input class="btn btn-warning" type="submit" value="Archive">
  </form>
    {% else %}
    <h1>Вам сюда нельзя</h1>
    {% endif %}
  <div>
    <a class="btn btn-sm btn-info" href="{% url 'showcase_app:question' pk=question.pk %}">Назад к вопросу</a>
  </div>
{% endblock %}

showcase_app/templates/showcase_app/question_detail.html
{% extends 'base.html' %}

{% block title %}
  Вопрос к Товару #{{ question.product_id }}
{% endblock %}

{% block body %}
  <h1>Вопрос к товару #{{ question.product_id }}, от пользователя <a href="{% url "user_app:userprofile" pk=question.user.pk %}">{{ question.user.username }}</a> </h1>
  <h2><code>{{ question.header }}</code></h2>
  <h3>Состав вопроса:</h3>
  <p>{{ question.body }}</p>
  <h3>Создан:</h3>
  <p>{{ question.created_at }}</p>

    <h3>Обновлен:</h3>
  <p>{{ question.updated_at }}</p>

    <h3>Ответы:</h3>
    <h3>________</h3>
        {% for obj in answer %}

            <h5>{{ obj.body }}</h5>
            <p>Ответ пользователя: <a href="{% url "user_app:userprofile" pk=obj.user.pk %}">{{ obj.user.username }}</a></p>
              {% if request.user.pk in product.user.pk or request.user.baseuser.moder or request.user.is_staff %}
            <a class="btn btn-warning" href="{% url 'showcase_app:delete-answer' pk=obj.pk %}">Архивировать</a>
              {% enif %}
            {{ obj.created_at }}
          <h3>________</h3>
        {% endfor %}
      <form method="POST">
        {% csrf_token %}

        {% if user.is_authenticated %}
        <div class="form-group">
            {{ form }}
            <button class="btn btn-info" type="submit">Отправить! </button>
            {% else %}
      <a
        class="btn btn-outline-primary"
        href="{% url 'login' %}">
        Login
      </a>
    {% endif %}
        </div>
      </form>




  <p>{{ form.question }}</p>
  <div>
    {% if request.user.pk in question.user.pk or request.user.baseuser.moder or request.user.is_staff %}
      <a class="btn btn-warning" href="{% url 'showcase_app:delete-question' pk=question.pk %}">Архивировать</a>
    {% endif %}
      <ul>
        <li>
          <a href="{% url 'showcase_app:product' pk=question.product_id %}">Назад к товару</a>
      </li>
      <li>
        <a href="{% url 'showcase_app:index' %}">Назад к витрине</a>
      </li>

    </ul>
  </div>
{% endblock %}

showcase_app/templates/showcase_app/question_list.html
{% extends 'base.html' %}

{% block title %}
  Вопросы
{% endblock %}

{% block body %}
  <h1>Вопросы:</h1>

  <div>
    <ul>
      {% for obj in question_list %}

            <a class="text-decoration-none"
               href="{% url 'showcase_app:question' pk=obj.pk %}"
        ><h4>{{ obj.header }}</h4></a>
            <h5>{{ obj.body }}</h5>

          <p>{{ obj.user.username }} {{ obj.created_at }} </p>
          <a href="{% url 'showcase_app:product' pk=obj.product_id %}">К товару</a>
          <h3>________</h3>
          {% empty %}
          <h3>Пока пусто!</h3>
        {% endfor %}
     <li>
        <a href="{% url 'showcase_app:index' %}">Назад к витрине</a>
      </li>
    </ul>
  </div>

{% endblock %}